/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DaoClasse.AdminDao;
import DaoClasse.ClientDao;
import DaoClasse.PrestataireDao;
import DaoInterface.IAdminDao;
import DaoInterface.IClientDao;
import DaoInterface.IPrestataireDao;
import Entites.Admin;
import Entites.Client;
import Entites.Prestataire;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GaiaDev
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Auth
     */
    Thread clock;
    public static Client c=null;
    public static Admin a=null;
    public static Prestataire p=null ;
    
    public void currentdate()
    {
    
    clock=new Thread(){
        @Override
        public void run()
        {
        for(;;){
            Calendar cal1 = new GregorianCalendar();
    
    

    int Year=cal1.get(Calendar.YEAR);
    int Month=(cal1.get(Calendar.MONTH)+1);
    int Days=cal1.get(Calendar.DAY_OF_MONTH);
    int Second=cal1.get(Calendar.SECOND);
    int minute=cal1.get(Calendar.MINUTE);
    int hours=cal1.get(Calendar.HOUR);
    String ch="Date = "+Year+"/"+Month+"/"+Days+"    Time = "+hours+":"+minute+":"+Second;
            System.out.println(ch);
    jLabel4.setText(ch);
            try {
                sleep(1000)  ;
            } catch (InterruptedException ex) {
                Logger.getLogger(AcceuilClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
    
    
        }
    };
    clock.start();
    
}
    public Authentification() {
        initComponents();
        setBounds(300, 100, 996, 613);
        currentdate();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonsinscrirre = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jbuttonConnexion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(996, 613));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.setLayout(null);

        jTextField1.setText("Email");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(110, 50, 190, 30);

        jPasswordField1.setText("Password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(110, 110, 190, 30);

        jButtonsinscrirre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonsinscrirre.setText("S'inscrire");
        jButtonsinscrirre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsinscrirreActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsinscrirre);
        jButtonsinscrirre.setBounds(110, 260, 190, 25);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAnnuler);
        jButtonAnnuler.setBounds(260, 170, 90, 23);

        jbuttonConnexion.setText("Connexion");
        jbuttonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonConnexionActionPerformed(evt);
            }
        });
        jPanel1.add(jbuttonConnexion);
        jbuttonConnexion.setBounds(70, 170, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1424723048_Login.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 50, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1424724875_lock.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 50, 60);

        jButton1.setText("Se Connecter avec Facebook");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 220, 190, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(360, 100, 410, 350);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 520, 330, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        /* jTextField1.setText("");
        jTextField2.setText("");
        jTextField1.setBackground(Color.WHITE);
        jTextField2.setBackground(Color.WHITE);
        */
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jbuttonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonConnexionActionPerformed
        
        IClientDao clientDAO = new ClientDao();
        List<Client> clients = clientDAO.retrieveAllClient();

        IPrestataireDao prestataireDAO = new PrestataireDao();
        List<Prestataire> prestataires = prestataireDAO.retrieveAllPrestataire();

        IAdminDao adminDao = new AdminDao();
        List<Admin> administrateurs = adminDao.retriveAllAdmin();

        for (Admin administrateur : administrateurs) {

            if ((jTextField1.getText().equalsIgnoreCase(administrateur.getNom()))&&(jPasswordField1.getText().equals(administrateur.getPwd())))
            {
                Authentification.a=administrateur;
                new AccueilAdmin().setVisible(true);
                this.setVisible(false);
            }
        }

         for (Prestataire prestataire : prestataires) {
            if ((jTextField1.getText().equals(prestataire.getUsername()))&&(jPasswordField1.getText().equals(prestataire.getPassword())))
            {
                if (prestataire.getLocked()==1) {
                                    Authentification.p=prestataire;

                            JOptionPane.showMessageDialog(rootPane, "Votre compte est bloque");

                }else if (prestataire.getEnabled()==0) {
                                                        Authentification.p=prestataire;

                                                JOptionPane.showMessageDialog(rootPane, "Votre compte est desactiver");

                }else
                {
                
                Authentification.p=prestataire;
                
                new AccueilPrestataire().setVisible(true);
                this.setVisible(false);

            }}

        }
        for (Client client : clients) {
            if ((jTextField1.getText().equals(client.getUsername()))&&(jPasswordField1.getText().equals(client.getPassword())))
            {
                 if (client.getLocked()==1) {
                                     Authentification.c=client;

                            JOptionPane.showMessageDialog(rootPane, "Votre compte est bloquÃ©");

                }else if (client.getEnabled()==0) {
                                    Authentification.c=client;
                                                JOptionPane.showMessageDialog(rootPane, "Votre compte est dÃ©sactiver");

                }else
                {
                
                Authentification.c=client;
                clock.stop();

                new AcceuilClient().setVisible(true);
                this.setVisible(false);

            }}

        }
        if ((Authentification.c==null)&&(Authentification.a==null)&&(Authentification.p==null))
                {
                       Voice v;
                    VoiceManager vm=VoiceManager.getInstance();
                    v=vm.getVoice("kevin16");
                    v.allocate();
                    
                    v.speak(" Email or Password Incorrect");
                   
        JOptionPane.showMessageDialog(rootPane, "Email ou mot de passe incorrect");
    }//GEN-LAST:event_jbuttonConnexionActionPerformed
    }
    private void jButtonsinscrirreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsinscrirreActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new Inscription().setVisible(true);
    }//GEN-LAST:event_jButtonsinscrirreActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(jTextField1.getText().trim().equals("Email"))
        {
           jTextField1.setText("");
    }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if(jTextField1.getText().trim().equals(""))
        {
           jTextField1.setText("Email");
    }
    }//GEN-LAST:event_jTextField1FocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jButtonsinscrirre.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        if(jPasswordField1.getText().trim().equals("Password"))
        {
           jPasswordField1.setText("");
    }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
         if(jPasswordField1.getText().trim().equals(""))
        {
           jPasswordField1.setText("Password");
    }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          new GraphReaderExample("CAACEdEose0cBADUdMzZBykwiJASJSYPQfHQ9ePyYDQsbjFl1jmc4qHD8n7SoLonxaV4W8airu78sM"
                 + "GrF6crC5surTRp7PAabKkEta5QIoDAExjtQx94IUtUcFzSefaR5M5iV9omFMNW4Uj3H2Fl2ZAgZCVUVo2OxwmFeXOi"
                 + "4AS1nUYCRlNqbdnQlX1Xws0ntAUZALfrMFZBJiWhHbdAhKmtKxmKX0Re0ZD").runEverything();
        JOptionPane.showMessageDialog(rootPane, "inscription effectué avec succés ");
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonsinscrirre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbuttonConnexion;
    // End of variables declaration//GEN-END:variables
}
